const createUser = `
    CREATE TABLE USER (
        USER_ID INT(5) NOT NULL AUTO_INCREMENT,
        USERNAME VARCHAR(255) NOT NULL,
        PASSWORD VARCHAR(255) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        TIMESTAMPED DATETIME NOT NULL,
        PRIMARY KEY (USER_ID)
    );
`


module.exports = {createUser} 